language: java
jdk: oraclejdk8
branches:
  only: master
install: true
script: ".travis/build.sh"
after_success: ".travis/notify.sh Travis-Success"
after_failure: ".travis/notify.sh Travis-Failure"
env:
  global:
  - secure: M1abL+9MkA7Ig+lbepQyFJJhkssRgG6SbMCw7fxKXsJGQbUSnb4RGbMOAdhIgKw2sydDoqprl25ZQJarIWPfwcWQP6kWtQ+CBug57kUAcbwOBC5R5gBz3dfMFth6C118Q+6ypMtJ2dSEAGQZkkcKObATunZQBqdTpfCrwGSVJQ4=
  - secure: cyDfUcoCslwclSdsdf+kMe9ZyKaLQSoD09OPJ2zhxG7K1VXRlL5aFwWs7Y3Avb81UtRZ31lyTJH/dLBU7IgmwIEH8iP5PGu0ffXs/aL1sEAsfSVlPRRN1QPjlTTxlqFGT248tUrpsAyI/XV06L+J2fmN243eysCrHZdGFTRm5BY=
